crate::doc_page!(
    "wasm-bindgen",
    "/zh-Hans/docs/concepts/basic-web-technologies/wasm-bindgen",
    Content::new(vec![
        p![link!("https://github.com/rustwasm/wasm-bindgen", code("wasm-bindgen")), link!("https://rustwasm.github.io/", "The Rust and WebAssembly Working Group"), "."],
        p!["Yew uses ", code("wasm-bindgen"), " to interact with the browser through a number of crates:"],
        ul![li![link!("https://crates.io/crates/js-sys", code("js-sys"))], li![link!("https://crates.io/crates/wasm-bindgen", code("wasm-bindgen"))], li![link!("https://crates.io/crates/wasm-bindgen-futures", code("wasm-bindgen-futures"))], li![link!("https://crates.io/crates/web-sys", code("web-sys"))]],
        p![code("wasm-bindgen"), " APIs with Yew. For a more in-depth guide to ", code("wasm-bindgen"), " and its associated crates then check out ", link!("https://wasm-bindgen.github.io/wasm-bindgen/", "The wasm-bindgen Guide"), "."],
        p!["For documentation on the above crates check out ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/index.html", "wasm-bindgen docs.rs"), "."],
        admonition!(AdmonitionType::Tip, None, p!["Use the ", code("wasm-bindgen"), code("wasm-bindgen"), "."]),
        h2![link!("https://crates.io/crates/wasm-bindgen", "wasm-bindgen")],
        p![code("wasm-bindgen"), " crate and that is the macro and some types/traits you will see pop up again and again."],
        h3!["#[wasm_bindgen] macro"],
        p!["The ", code("#[wasm_bindgen]"), code("js-sys"), " and ", code("web-sys"), " crates expose ", code("wasm-bindgen"), " definitions for built-in JavaScript types and browser APIs."],
        p!["Let's go over a simple example of using the ", code("#[wasm-bindgen]"), " macro to import some specific flavours of the ", link!("https://developer.mozilla.org/en-US/docs/Web/API/Console/log", code("console.log")), " function."],
        p!["This example was adapted from ", link!("https://wasm-bindgen.github.io/wasm-bindgen/examples/console-log.html", "1.2 Using console.log of The wasm-bindgen Guide"), "."],
        h3!["Simulating inheritance"],
        p![code("wasm-bindgen"), " you can also add attributes that describe their inheritance."],
        p!["In Rust, this inheritance is represented using the ", link!("https://doc.rust-lang.org/std/ops/trait.Deref.html", code("Deref")), " and ", link!("https://doc.rust-lang.org/std/convert/trait.AsRef.html", code("AsRef")), " traits. An example of this might help; so say you have three types ", code("A"), ", ", code("B"), ", and ", code("C"), " where ", code("C"), " extends ", code("B"), " which in turn extends ", code("A"), "."],
        p!["When importing these types the ", code("#[wasm-bindgen]"), " macro will implement the ", code("Deref"), " and ", code("AsRef"), " traits in the following way:"],
        ul![li![code("C"), " can ", code("Deref"), " to ", code("B")], li![code("B"), " can ", code("Deref"), " to ", code("A")], li![code("C"), " can be ", code("AsRef"), " to ", code("B")], li!["Both ", code("C"), " & ", code("B"), " can be ", code("AsRef"), " to ", code("A")]],
        p!["These implementations allow you to call a method from ", code("A"), " on an instance of ", code("C"), " and to use ", code("C"), " as if it was ", code("&B"), " or ", code("&A"), "."],
        p!["It is important to note that every single type imported using ", code("#[wasm_bindgen]"), " has the same root type, you can think of it as the ", code("A"), " in the example above, this type is ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsValue.html", code("JsValue")), " which has its section below."],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/reference/attributes/on-js-imports/extends.html", "extends section in The wasm-bindgen Guide")],
        h3![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsValue.html", "JsValue")],
        p!["This is a representation of an object owned by JavaScript, this is a root catch-all type for ", code("wasm-bindgen"), ". Because JavaScript does not have a strong type system, any type that comes from ", code("wasm-bindgen"), " is a ", code("JsValue"), code("JsValue"), ". If you are working with imported functions or types that accept a ", code("JsValue"), ", then any imported value is ", italic!["technically"], " valid."],
        p!["Even though ", code("JsValue"), " may be accepted by a JS function, that function may still only ", italic!["actually"], " accept certain types. Passing an incorrect ", code("JsValue"), " can lead to an exception which triggers a panic - so when using raw ", code("wasm-bindgen"), " APIs, check your JavaScript's documentation for types of inputs that will cause an exception (and a panic)."],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsValue.html", "JsValue documentation"), "."],
        h3![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/trait.JsCast.html", "JsCast")],
        p![code("JsCast"), code("JsCast"), " to jump from one type to the other. It is a nice trait to get to know when working with ", code("web-sys"), ", ", code("wasm_bindgen"), ", ", code("js-sys"), " - you will notice lots of types will implement ", code("JsCast"), " from those crates."],
        p![code("JsCast"), link!("https://doc.rust-lang.org/std/option/enum.Option.html", code("Option")), " and ", link!("https://doc.rust-lang.org/std/result/enum.Result.html", code("Result")), "."],
        p!["A common example of this in ", link!("/docs/0.21/concepts/basic-web-technologies/web-sys", code("web-sys")), " is when you are trying to get the target of an event. You might know what the target element is, but the ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/web_sys/struct.Event.html", code("web_sys::Event")), " API will always return an ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/web_sys/struct.Event.html#method.target", code("Option<web_sys::EventTarget>")), ". You will need to cast it to the element type so you can call its methods."],
        p!["The ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/trait.JsCast.html#method.dyn_ref", code("dyn_ref")), " method is a checked cast that returns an ", code("Option<&T>"), ", which means the original type can be used again if the cast failed and thus returned ", code("None"), ". The ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/trait.JsCast.html#method.dyn_into", code("dyn_into")), " method will consume ", code("self"), ", as per convention for ", code("into"), " methods in Rust, and the type returned is ", code("Result<T, Self>"), ". If the casting fails, the original ", code("Self"), " value is returned in ", code("Err"), ". You can try again or do something else with the original type."],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/trait.JsCast.html", "JsCast documentation"), "."],
        h3![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/closure/struct.Closure.html", "Closure")],
        p!["The ", code("Closure"), code("'static"), " lifetime for soundness reasons."],
        p![code("Closure"), " has been dropped will raise an exception."],
        p![code("Closure"), " is often used when you are working with a ", code("js-sys"), " or ", code("web-sys"), " API that accepts a type ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/js_sys/struct.Function.html", code("&js_sys::Function")), ". An example of using a ", code("Closure"), " in Yew can be found in the ", link!("/docs/0.21/concepts/html/events#using-closure-verbose", "Using Closure section"), " on the ", link!("/docs/0.21/concepts/html/events", "Events"), " page."],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen/closure/struct.Closure.html", "Closure documentation"), "."],
        h2![link!("https://crates.io/crates/js-sys", "js-sys")],
        p!["The ", code("js-sys")],
        p!["This does not include any web APIs; that's what ", link!("/docs/0.21/concepts/basic-web-technologies/web-sys", code("web-sys")), " is for!"],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/js_sys/index.html", "js-sys documentation"), "."],
        h2![link!("https://crates.io/crates/wasm-bindgen-futures", "wasm-bindgen-futures")],
        p!["The ", code("wasm-bindgen-futures"), " crate provides a bridge for working with JavaScript Promise types as a Rust ", link!("https://doc.rust-lang.org/stable/std/future/trait.Future.html", code("Future"))],
        p!["There are three main interfaces in this crate currently:"],
        ol![li![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen_futures/struct.JsFuture.html", code("JsFuture")), " - A type that is constructed with a ", link!("https://wasm-bindgen.github.io/wasm-bindgen/api/js_sys/struct.Promise.html", code("Promise")), " and can then be used as a ", code("Future<Output=Result<JsValue, JsValue>>"), ". This Future will resolve to ", code("Ok"), " if the Promise is resolved and ", code("Err"), " if the Promise is rejected, containing the resolved or rejected value from the Promise respectively."], li![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.future_to_promise.html", code("future_to_promise")), " - Converts a Rust ", code("Future<Output=Result<JsValue, JsValue>>"), " into a JavaScript ", code("Promise"), ". The future's result will translate to either a resolved or rejected Promise in JavaScript."], li![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html", code("spawn_local")), " - Spawns a ", code("Future<Output = ()>"), " on the current thread. This is the best way to run a Future in Rust without sending it to JavaScript."]],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen_futures/index.html", "wasm-bindgen-futures documentation"), "."],
        h3![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html", "spawn_local")],
        p![code("spawn_local"), " is going to be the most commonly used part of the ", code("wasm-bindgen-futures"), " crate in Yew as this helps when using libraries that have async APIs."],
        p!["Yew has also added support for futures in certain APIs, most notably you can create a ", code("callback_future"), " which accepts an ", code("async"), " block - this uses ", code("spawn_local"), " internally."],
        p![link!("https://wasm-bindgen.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html", "spawn_local documentation"), "."]
    ])
);
