crate::doc_page!(
    "",
    "/zh-Hans/docs/more/roadmap",
    Content::new(vec![
        h1!["路线图"],
        h2!["`v1.0.0`"],
        h3!["规划中的功能"],
        ul![
            li![
                "标记 key 的列表项：",
                link!(
                    "https://github.com/yewstack/yew/issues/479",
                    "https://github.com/yewstack/yew/issues/479",
                ),
            ],
            li![
                "路由：",
                link!(
                    "https://github.com/yewstack/yew_router",
                    "https://github.com/yewstack/yew_router",
                ),
            ],
        ],
        h3!["生产环境准备"],
        ul![
            li!["浏览器兼容性"],
            li!["提高 Yew 框架的测试覆盖率"],
            li![
                "增加性能基准测试：",
                link!(
                    "https://github.com/yewstack/yew/issues/5",
                    "https://github.com/yewstack/yew/issues/5",
                ),
            ],
        ],
        h3!["指南"],
        ul![
            li![
                "最佳实践：",
                link!(
                    "https://yew.rs/optimizations",
                    "https://yew.rs/optimizations",
                ),
            ],
            li!["端到端教程"],
            li!["Futures / 并发"],
            li!["CSS / 样式"],
            li!["测试"],
            li!["状态管理"],
        ],
        h2!["未来"],
        h3!["潜在功能"],
        ul![
            li![
                "服务端渲染：",
                link!(
                    "https://github.com/yewstack/yew/issues/41",
                    "https://github.com/yewstack/yew/issues/41",
                ),
            ],
            li![
                "组件库：",
                link!(
                    "https://github.com/yewstrap/yewstrap",
                    "https://github.com/yewstrap/yewstrap",
                ),
            ],
            li![
                "代码分割：",
                link!(
                    "https://github.com/yewstack/yew/issues/599",
                    "https://github.com/yewstack/yew/issues/599",
                ),
            ],
            li![
                "允许不同的虚拟 DOM 后端：",
                link!(
                    "https://github.com/yewstack/yew/issues/482",
                    "https://github.com/yewstack/yew/issues/482",
                ),
            ],
            li![
                "反思 Services：",
                link!(
                    "https://github.com/yewstack/yew/issues/364",
                    "https://github.com/yewstack/yew/issues/364",
                ),
            ],
            li![
                "成熟的工具包：",
                link!(
                    "https://github.com/yewstack/yewtil",
                    "https://github.com/yewstack/yewtil",
                ),
            ],
            li![
                "HTML 模板备选方案：",
                link!(
                    "https://github.com/yewstack/yew/issues/438",
                    "https://github.com/yewstack/yew/issues/438",
                ),
            ],
        ],
    ])
    .with_description("The planned feature roadmap for the Yew framework")
);
