crate::doc_page!(
    "Deployment",
    "/zh-Hans/docs/more/deployment",
    Content::new(vec![
        p![text(
            "When you are ready to deploy your Yew application to a server, you have various \
             options for deployment."
        )],
        p![
            code("trunk build --release"),
            text(" builds your app in release mode. Set up your HTTP server so that it serves "),
            code("index.html"),
            text(" whenever your site is visited, and requests to static paths like "),
            code("index_<hash>.js"),
            text(" and "),
            code("index_bg_<hash>.wasm"),
            text(
                " are served with the contents of their respective contents from the dist \
                 directory generated by trunk."
            )
        ],
        admonition!(
            AdmonitionType::Important,
            Some("A note about `trunk serve --release`"),
            p![
                text("Do "),
                bold![text("not")],
                text(" use "),
                code("trunk serve --release"),
                text(
                    " to serve your application in production. It should only be used for testing \
                     the release build during development"
                )
            ]
        ),
        h2![text("Server configuration")],
        h3![
            text("Serving "),
            code("index.html"),
            text(" as a fallback")
        ],
        p![
            text("If the application uses the "),
            link!("/docs/0.21/concepts/router", text("Yew router")),
            text(", you must configure the server to return the "),
            code("index.html"),
            text(" when asked for a file that it does not have.")
        ],
        p![
            text("An application with Yew router is built as a "),
            link!(
                "https://developer.mozilla.org/en-US/docs/Glossary/SPA",
                text("Single Page Application (SPA)")
            ),
            text(
                ". When the user navigates to a URL from within a running client, the router \
                 interprets the URL and routes to that page."
            )
        ],
        p![text(
            "But on a fresh load, such as when navigating to the page by entering it in the \
             address bar or refreshing the page, all of these actions are handled by the browser \
             itself, outside the running application. The browser makes a direct request to the \
             server for that URL, bypassing the router. A wrongly configured server would return \
             with the status 404 - Not Found."
        )],
        p![
            text("By returning "),
            code("index.html"),
            text(" instead, the app loads as it normally would, as if the request was for "),
            code("/"),
            text(" until the router notices that the route is "),
            code("/show/42"),
            text(" and displays the appropriate contents.")
        ],
        h3![text(
            "Configuring correct MIME-type for Web Assembly asset"
        )],
        p![
            text("The WASM files must be served with the "),
            link!(
                "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type",
                text("Content-Type header")
            ),
            text(" set to "),
            code("application/wasm"),
            text(" MIME-type.")
        ],
        p![text(
            "Most servers and hosting services already do this by default. If yours does not, \
             consult its documentation. An incorrect MIME type will, in most web browsers, result \
             in an error similar to the following:"
        )],
        code_block(
            "text",
            r#"`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: WebAssembly: Response has unsupported MIME type 'text/plain' expected 'application/wasm'"#
        ),
        h2![text("Building for Relative Paths")],
        p![
            text("By default, trunk will assume that your site is being served at "),
            code("/"),
            text(" and build the site accordingly. This behavior can be overridden by adding "),
            code("<base data-trunk-public-url />"),
            text(" to the "),
            code("index.html"),
            text(" file. Trunk rewrites this tag to contain the value passed to "),
            code("--public-url"),
            text(". Yew router automatically detects the presence of "),
            code("<base />"),
            text(" and handles it appropriately.")
        ],
        h2![text(
            "Customizing behavior using environment variables"
        )],
        p![
            text(
                "It is common to customize the build environment by using environment variables. \
                 Since the app is run in a browser, we cannot read the environment variables at \
                 runtime. The "
            ),
            link!(
                "https://doc.rust-lang.org/std/macro.env.html",
                code("std::env!")
            ),
            text(
                " macro can be used to obtain a value of an environment variable at compile time."
            )
        ]
    ])
);
