crate::doc_page!(
    "How it works",
    "/zh-Hans/docs/advanced-topics/how-it-works",
    Content::new(vec![
        h1!["底层库的内部细节"],
        h2!["Under the hood of the `html!` macro"],
        p![
            "The ",
            code("html!"),
            " macro turns code written in a custom HTML-like syntax into valid Rust code. Using \
             this macro is not necessary for developing Yew applications, but it is recommended. \
             The code generated by this macro makes use of the public Yew library API which can \
             be used directly if you wish. Note that some methods used are undocumented \
             intentionally to avoid accidental misuse. With each update of ",
            code("yew-macro"),
            ", the generated code will be more efficient and handle any breaking changes without \
             many (if any) modifications to the ",
            code("html!"),
            " syntax."
        ],
        p![
            "Because the ",
            code("html!"),
            " macro allows you to write code in a declarative style, your UI layout code will \
             closely match the HTML that is generated for the page. This becomes increasingly \
             useful as your application gets more interactive and your codebase gets larger. \
             Rather than manually writing all of the code to manipulate the DOM yourself, the \
             macro will handle it for you."
        ],
        p![
            "Using the ",
            code("html!"),
            " macro can feel pretty magical, but it has nothing to hide. If you are curious about \
             how it works, try expanding the ",
            code("html!"),
            " macro calls in your program. There is a useful command called ",
            code("cargo expand"),
            " which allows you to see the expansion of Rust macros. ",
            code("cargo expand"),
            " does not ship with ",
            code("cargo"),
            " by default so you will need to install it with ",
            code("cargo install cargo-expand"),
            " if you have not already. ",
            link!("https://rust-analyzer.github.io/", "Rust-Analyzer"),
            " also provides a mechanism for ",
            link!(
                "https://rust-analyzer.github.io/manual.html#expand-macro-recursively",
                "obtaining macro output from within an IDE"
            ),
            "."
        ],
        p![
            "Output from the ",
            code("html!"),
            " macro is often pretty terse! This is a feature: machine-generated code can \
             sometimes clash with other code in an application. To prevent issues, ",
            code("proc_macro"),
            " \"hygiene\" is adhered to. Some examples include:"
        ],
        ol![
            li![
                "Instead of using ",
                code("yew::<module>"),
                " the macro generates ",
                code("::yew::<module>"),
                " to make sure that the Yew package is referenced correctly. This is also why ",
                code("::alloc::vec::Vec::new()"),
                " is called instead of just ",
                code("Vec::new()"),
                "."
            ],
            li![
                "Due to potential trait method name collisions, ",
                code("<Type as Trait>"),
                " is used to make sure that we are using members from the correct trait."
            ]
        ],
        h2!["What is a virtual DOM?"],
        p![
            "The DOM (\"document object model\") is a representation of the HTML content that is \
             managed by the browser for your web page. A \"virtual\" DOM is simply a copy of the \
             DOM that is held in application memory. Managing a virtual DOM results in a higher \
             memory overhead, but allows for batching and faster reads by avoiding or delaying \
             the use of browser APIs."
        ],
        p![
            "Having a copy of the DOM in memory can be helpful for libraries that promote the use \
             of declarative UIs. Rather than needing specific code for describing how the DOM \
             should be modified in response to a user event, the library can use a generalized \
             approach with DOM \"diffing\". When a Yew component is updated and wants to change \
             how it is rendered, the Yew library will build a second copy of the virtual DOM and \
             directly compare it to a virtual DOM which mirrors what is currently on screen. The \
             \"diff\" (or difference) between the two can be broken down into incremental updates \
             and applied in a batch with browser APIs. Once the updates are applied, the old \
             virtual DOM copy is discarded and the new copy is saved for future diff checks."
        ],
        p![
            "This \"diff\" algorithm can be optimized over time to improve the performance of \
             complex applications. Since Yew applications are run with WebAssembly, we believe \
             that Yew has a competitive edge to adopt more sophisticated algorithms in the future."
        ],
        p![
            "The Yew virtual DOM is not exactly one-to-one with the browser DOM. It also includes \
             \"lists\" and \"components\" for organizing DOM elements. A list can simply be an \
             ordered list of elements but can also be much more powerful. By annotating each list \
             element with a \"key\", application developers can help Yew make additional \
             optimizations to ensure that when a list changes, the least amount of work is done \
             to calculate the diff update. Similarly, components provide custom logic to indicate \
             whether a re-render is required to help with performance."
        ],
        h2!["Yew scheduler and component-scoped event loop"],
        p![
            "_Contribute to the docs – explain how ",
            code("yew::scheduler"),
            " and ",
            code("yew::html::scope"),
            " work in depth_"
        ],
        h2!["Further reading"],
        ul![
            li![link!(
                "https://doc.rust-lang.org/stable/book/ch19-06-macros.html",
                "More information about macros from the Rust Book"
            )],
            li![link!(
                "https://github.com/dtolnay/cargo-expand",
                "More information about cargo-expand"
            )],
            li![link!(
                "https://docs.rs/yew/*/yew/virtual_dom/index.html",
                "The API documentation for yew::virtual_dom"
            )]
        ]
    ])
);
