crate::doc_page!(
    "狀態",
    "/zh-Hant/docs/concepts/function-components/state",
    Content::new(vec![
        h2(vec![text("如何儲存狀態的一般視圖")]),
        p(vec![text(
            "這個表格可以作為一個指南，幫助您決定哪種狀態儲存類型最適合您的用例：",
        )]),
        p(vec![
            text("| Hook             | 類型                       | 何時渲染?                        | 作用域                   | | ---------------- | -------------------------- | -------------------------------- | ------------------------ | | "),
            text("[use_state]      | "),
            code("T"),
            text("                        | 被設定一個值                     | 組件內部實例             | | "),
            text("[use_state_eq]   | "),
            code("T: PartialEq"),
            text("             | 被設定一個不同的值               | 組件內部實例             | | "),
            text("[use_reducer]    | "),
            code("T: Reducible"),
            text("             | 被呼叫歸納                       | 組件內部實例             | | "),
            text("[use_reducer_eq] | "),
            code("T: Reducible + PartialEq"),
            text(" | 被呼叫歸納，歸納後的值與之前不同 | 組件內部實例             | | "),
            text("[use_memo]       | "),
            code("Deps -> T"),
            text("                | 依賴項發生變化                   | 組件內部實例             | | "),
            text("[use_callback]   | "),
            code("Deps -> Callback<E>"),
            text("      | 依賴項發生變化                   | 組件內部實例             | | "),
            text("[use_mut_ref]    | "),
            code("T"),
            text("                        | -                                | 組件內部實例             | | "),
            text("全域靜態常數     | "),
            code("T"),
            text("                        | -                                | 全域，任何位置都可以使用 |"),
        ]),
        p(vec![
            text("[use_state]: https://yew-rs-api.web.app/next/yew/functional/fn.use_state.html "),
            text("[use_state_eq]: https://yew-rs-api.web.app/next/yew/functional/fn.use_state_eq.html "),
            text("[use_reducer]: https://yew-rs-api.web.app/next/yew/functional/fn.use_reducer.html "),
            text("[use_reducer_eq]: https://yew-rs-api.web.app/next/yew/functional/fn.use_reducer_eq.html "),
            text("[use_memo]: https://yew-rs-api.web.app/next/yew/functional/fn.use_memo.html "),
            text("[use_callback]: https://yew-rs-api.web.app/next/yew/functional/fn.use_callback.html "),
            text("[use_mut_ref]: https://yew-rs-api.web.app/next/yew/functional/fn.use_mut_ref.html"),
        ]),
    ])
);
