crate::doc_page!(
    "狀態",
    "/zh-Hant/docs/concepts/function-components/state",
    Content::new(vec![
        h2!["如何儲存狀態的一般視圖"],
        p!["這個表格可以作為一個指南，幫助您決定哪種狀態儲存類型最適合您的用例："],
        p![
            "| Hook             | 類型                       | 何時渲染?                        | 作用域                   | | ---------------- | -------------------------- | -------------------------------- | ------------------------ | | ",
            "[use_state]      | ",
            code("T"),
            "                        | 被設定一個值                     | 組件內部實例             | | ",
            "[use_state_eq]   | ",
            code("T: PartialEq"),
            "             | 被設定一個不同的值               | 組件內部實例             | | ",
            "[use_reducer]    | ",
            code("T: Reducible"),
            "             | 被呼叫歸納                       | 組件內部實例             | | ",
            "[use_reducer_eq] | ",
            code("T: Reducible + PartialEq"),
            " | 被呼叫歸納，歸納後的值與之前不同 | 組件內部實例             | | ",
            "[use_memo]       | ",
            code("Deps -> T"),
            "                | 依賴項發生變化                   | 組件內部實例             | | ",
            "[use_callback]   | ",
            code("Deps -> Callback<E>"),
            "      | 依賴項發生變化                   | 組件內部實例             | | ",
            "[use_mut_ref]    | ",
            code("T"),
            "                        | -                                | 組件內部實例             | | ",
            "全域靜態常數     | ",
            code("T"),
            "                        | -                                | 全域，任何位置都可以使用 |",
        ],
        p![
            "[use_state]: https://yew-rs-api.web.app/next/yew/functional/fn.use_state.html ",
            "[use_state_eq]: https://yew-rs-api.web.app/next/yew/functional/fn.use_state_eq.html ",
            "[use_reducer]: https://yew-rs-api.web.app/next/yew/functional/fn.use_reducer.html ",
            "[use_reducer_eq]: https://yew-rs-api.web.app/next/yew/functional/fn.use_reducer_eq.html ",
            "[use_memo]: https://yew-rs-api.web.app/next/yew/functional/fn.use_memo.html ",
            "[use_callback]: https://yew-rs-api.web.app/next/yew/functional/fn.use_callback.html ",
            "[use_mut_ref]: https://yew-rs-api.web.app/next/yew/functional/fn.use_mut_ref.html",
        ],
    ])
);
