pub mod pages;
pub mod sidebar_data;

#[macro_export]
macro_rules! doc_page {
    ($title:expr, $path:expr, $content:expr) => {
        #[allow(unused_imports)]
        use yew::prelude::*;
        #[allow(unused_imports)]
        use yew_site_lib::content::*;
        #[allow(unused_imports)]
        use yew_site_lib::Layout;
        #[allow(unused_imports)]
        use $crate::sidebar_data::docs_sidebar;
        pub fn page_content() -> yew_site_lib::Content {
            $content
        }

        #[component]
        pub fn Page() -> Html {
            let content: yew_site_lib::Content = page_content();
            let toc = content.toc_entries();
            let markdown = content.to_markdown();
            html! {
                <Layout title={$title} sidebar={docs_sidebar()} active_sidebar_path={$path} active_nav="Docs" doc_version="0.21" lang="zh-Hans" markdown={markdown} toc={toc}>
                    { content.to_html() }
                </Layout>
            }
        }
    };
}

#[cfg(feature = "ssr")]
pub async fn render_pages() -> Vec<(&'static str, String, String)> {
    let mut pages = Vec::new();
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/children",
        pages::advanced_topics::children::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/how-it-works",
        pages::advanced_topics::how_it_works::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/immutable",
        pages::advanced_topics::immutable::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/optimizations",
        pages::advanced_topics::optimizations::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/portals",
        pages::advanced_topics::portals::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/server-side-rendering",
        pages::advanced_topics::server_side_rendering::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components/callbacks",
        pages::advanced_topics::struct_components::callbacks::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components/hoc",
        pages::advanced_topics::struct_components::hoc::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components",
        pages::advanced_topics::struct_components::introduction::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components/lifecycle",
        pages::advanced_topics::struct_components::lifecycle::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components/properties",
        pages::advanced_topics::struct_components::properties::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components/refs",
        pages::advanced_topics::struct_components::refs::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/advanced-topics/struct-components/scope",
        pages::advanced_topics::struct_components::scope::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/agents",
        pages::concepts::agents::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/basic-web-technologies/css",
        pages::concepts::basic_web_technologies::css::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/basic-web-technologies/html",
        pages::concepts::basic_web_technologies::html::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/basic-web-technologies/js",
        pages::concepts::basic_web_technologies::js::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/basic-web-technologies/wasm-bindgen",
        pages::concepts::basic_web_technologies::wasm_bindgen::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/basic-web-technologies/web-sys",
        pages::concepts::basic_web_technologies::web_sys::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/contexts",
        pages::concepts::contexts::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/callbacks",
        pages::concepts::function_components::callbacks::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/children",
        pages::concepts::function_components::children::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/communication",
        pages::concepts::function_components::communication::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/generics",
        pages::concepts::function_components::generics::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/hooks/custom-hooks",
        pages::concepts::function_components::hooks::custom_hooks::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/hooks",
        pages::concepts::function_components::hooks::introduction::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components",
        pages::concepts::function_components::introduction::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/node-refs",
        pages::concepts::function_components::node_refs::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/properties",
        pages::concepts::function_components::properties::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/pure-components",
        pages::concepts::function_components::pure_components::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/function-components/state",
        pages::concepts::function_components::state::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/classes",
        pages::concepts::html::classes::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/components",
        pages::concepts::html::components::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/conditional-rendering",
        pages::concepts::html::conditional_rendering::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/elements",
        pages::concepts::html::elements::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/events",
        pages::concepts::html::events::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/fragments",
        pages::concepts::html::fragments::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html",
        pages::concepts::html::introduction::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/lists",
        pages::concepts::html::lists::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/html/literals-and-expressions",
        pages::concepts::html::literals_and_expressions::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/router",
        pages::concepts::router::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/concepts/suspense",
        pages::concepts::suspense::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/getting-started/build-a-sample-app",
        pages::getting_started::build_a_sample_app::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/getting-started/editor-setup",
        pages::getting_started::editor_setup::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/getting-started/examples",
        pages::getting_started::examples::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/getting-started",
        pages::getting_started::introduction::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/more/css",
        pages::more::css::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/more/debugging",
        pages::more::debugging::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/more/deployment",
        pages::more::deployment::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/more/roadmap",
        pages::more::roadmap::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/more/testing",
        pages::more::testing::Page
    ));
    pages.push(yew_site_lib::render_page!(
        "/zh-Hans/docs/0.21/tutorial",
        pages::tutorial::Page
    ));
    pages
}
