crate::doc_page!(
    "",
    "/zh-Hans/docs/getting-started/build-a-sample-app",
    Content::new(vec![
        h1!["第一个简单的 App"],
        p!["首先创建一个二进制项目:"],
        code_block(
            "bash",
            r#"cargo generate yewstack/yew-trunk-minimal-template"#
        ),
        p![
            "添加 ",
            code("yew"),
            " 到你的依赖库中（",
            link!["https://docs.rs/yew", "这里"],
            " 可以查看最新版本的 Yew）",
        ],
        code_block("text", r#"trunk serve"#),
        p!["将这份代码复制到你的 ", code("src/main.rs"), " 文件中:",],
        code_block("rust", r#"cargo new yew-app"#),
        p![
            "这份代码将构建你的称为 ",
            code("Model"),
            " 的 ",
            code("Component"),
            " 根组件，它会显示一个按钮，当你点击它时，",
            code("Model"),
            " 将会更新自己的状态。特别注意 ",
            code("main()"),
            " 中的 ",
            code("App::<Model>::new().mount_to_body()"),
            "，它会启动你的应用并将其挂载到页面的 ",
            code("<body>"),
            " 标签中。如果你想使用任何动态属性来启动应用程序，则可以使用 ",
            code("App::<Model>::new().mount_to_body_with_props(..)"),
            "。",
        ],
        h2!["运行你的应用程序!"],
        p![
            "启动并运行你的应用的最快方式就是使用 ",
            link!["https://github.com/koute/cargo-web", "cargo-web",],
            "。如果你还没有的话，请用 ",
            code("cargo install cargo-web"),
            " 命令来安装这个工具然后通过运行下述命令来构建和启动一个开发服务器：",
        ],
        code_block("bash", r#"cd yew-app"#),
        p![
            code("cargo-web"),
            " 将会自动为你添加 ",
            code("wasm32-unknown-unknown"),
            " 作为目标代码，然后构建你的应用，你的应用将默认在 ",
            "[http://\\",
            "[::1\\]:8000](http://",
            "[::1]:8000) 被访问。可以通过 ",
            code("cargo web start --help"),
            " 命令来获取更多选项和帮助。",
        ],
    ])
);
