crate::community_page!("Awesome Yew",
    Content::new(vec![
        h2!["Projects"],
        ul![
            li![link!["https://github.com/alelavelli/rust-fullstack-web-application", "Fullstack application with infrastructure"], " - Complete production-ready application with ", code("yew"), " as frontend, ", code("axum"), " as backend, ", code("docker compose"), " as infrastructure, ", code("mongodb"), " as database."],
            li![link!["https://github.com/jetli/rust-yew-realworld-example-app", "Realworld example"], " - Exemplary real world app built with Rust + Yew + WebAssembly. It utilizes Yew's latest ", code("function components"), " and ", code("hooks"), ". It also supports desktop application powered by ", link!["https://github.com/tauri-apps/tauri", "Tauri"], "."],
            li![link!["https://github.com/saschagrunert/webapp.rs", "webapp.rs"], " - A web application completely written in Rust, frontend is built with Yew."],
            li![link!["https://github.com/steadylearner/Rust-Full-Stack", "Rust-Full-Stack"], " - Easily testable and working Rust codes with blog posts to explain them."],
            li![link!["https://github.com/hgzimmerman/BucketQuestions", "Bucket Questions"], " - A webapp written entirely in Rust for a dumb party game."],
            li![link!["https://github.com/Extrawurst/rust-webview-todomvc-yew", "web-view todomvc desktop app"], " - Demo how to use yew for a todomvc that compiles to WebAssembly and is bundled as a lightweight(~2mb) desktop app by ", link!["https://github.com/Boscop/web-view", "web-view"], ", as an alternative to Electron, ", link!["https://github.com/Boscop/web-view", "web-view"], " also has a ", link!["https://github.com/Boscop/web-view/tree/master/webview-examples/examples#todo-yew", "demo"], "."],
            li![link!["https://github.com/hobofan/yew-react-example", "yew-react-example"], " - This project shows how to create a web app using a React component inside a Yew component."],
            li![link!["https://github.com/stkevintan/Kirk", "Kirk"], " - Just A Rust WebAssembly Blog."],
            li![link!["https://github.com/extraymond/rust-async-wasm-demo", "rust-async-wasm-demo"], " - Toy project to learn Rust and async that can be deployed to the web."],
            li![link!["https://github.com/tarkah/karaoke-rs", "karaoke-rs"], " - A simple, network enabled karaoke player in Rust."],
            li![link!["https://github.com/noc7c9/i-love-hue-rs", "I Love Hue! (rs)"], " - A clone of the mobile game I Love Hue in Yew (Rust)."],
            li![link!["https://github.com/spielrs/yew-styles-page", "yew-styles-page"], " - This is an initial project of a framework style for yew."],
            li![link!["https://github.com/jplatte/caniuse.rs", "caniuse.rs"], " - Rust feature search."],
            li![link!["https://github.com/Extrawurst/rust-electron-demo", "Rust electron yew demo"], " - An example of building a Rust based web app (Yew) into a native app using electron."],
            li![link!["https://github.com/jbowens/covplot", "covplot"], " - Live graphs of worldwide CoVID-19 data."],
            li![link!["https://github.com/fadhlika/tanoshi-web", "Tanoshi"], " - Tachiyomi-like web manga reader. Front-end for tanoshi."],
            li![link!["https://github.com/jgpaiva/minesweeper", "Minesweeper"], " - Minesweeper built with Rust, Yew and WebAssembly."],
            li![link!["https://github.com/Stigjb/freecell", "Freecell"], " - A patience game written in Rust and Yew."],
            li![link!["https://github.com/MTRNord/Daydream", "Daydream"], " - A small Matrix web client written in Rust."],
            li![link!["https://github.com/codec-abc/Yew-WebRTC-Chat", "Yew-WebRTC-Chat"], " - A simple WebRTC chat made with Yew."],
            li![link!["https://github.com/lukidoescode/yew-fullstack-boilerplate", "Yew Fullstack Boilerplate"], " - Highly opinionated boilerplate for creating full stack applications with Rust."],
            li![link!["https://github.com/Stigjb/chord-quiz", "Chord Quiz"], " - Practice recognizing chords in this Rust/Yew/WebAssembly app."],
            li![link!["https://github.com/sheshbabu/rustmart-yew-example", "RustMart"], " - Single Page Application (SPA) written using Rust, Wasm and Yew."],
            li![link!["https://github.com/alepez/devand", "DevAndDev"], " - A website where developers can find pair-programming partners. Written in Rust, Yew frontend."],
            li![link!["https://github.com/io12/yew-octicons", "yew-octicons"], " - An easy interface for using Octicons in Yew projects."],
            li![link!["https://github.com/pipe-fun/pipe", "Pipe"], " - This is a Rust / Wasm client web app which is a task control center."],
            li![link!["https://github.com/oovm/note-to-yew", "note-to-yew"], " - Convert your markups into Yew macro online, which is also made by Yew."],
            li![link!["https://github.com/getreu/ascii-hangman", "ASCII-Hangman"], " - Configurable Hangman game for children with ASCII-art rewarding."],
            li![link!["https://github.com/shaunbennett/dotdotyew", "dotdotyew"], " - ", link!["https://en.wikipedia.org/wiki/Dot-voting", "Dot-voting"], " using Yew, with Rust powering the backend API."],
            li![link!["https://github.com/dev-family/wasm-2048", "wasm-2048"], " - 2048 game implemented with Rust and Yew and compiled to Wasm."],
            li![link!["https://github.com/kamiyaa/website-wasm", "website-wasm"], " - My personal website written in Rust via Yew/Wasm."],
            li![link!["https://github.com/rayylee/keypress", "KeyPress"], " - A Rust WebAssembly Website example for practising english for chinese."],
            li![link!["https://github.com/anthhub/yew-train-ticket", "yew-train-ticket"], " - A Rust WebAssembly Webapp example basing Yew newest hooks and functional API, the code style is extremely like React Function Component."],
            li![link!["https://github.com/ivanschuetz/yew-d3-example", "yew-d3-example"], " - Showing a d3 chart with Yew."],
            li![link!["https://github.com/sanpii/oxfeed", "Oxfeed"], " - A feed reader written in Rust with a Yew frontend."],
            li![link!["https://github.com/LighghtEeloo/flow.er", "Flow.er"], " - A notebook app integrated with todo lists utility. Developed with Rust, WebAssembly, Yew and Trunk."],
            li![link!["https://github.com/vascokk/fullstack-rust", "Fullstack-Rust"], " - A Full Stack Rust application (Connect5 game) with Actix-web, Yew, Bulma CSS and Diesel."],
            li![link!["https://github.com/MAE664128/sea_battle", "Sea_battle"], " - A simple example of a sea battle game. Rust + Yew."],
            li![link!["https://github.com/zzy/tide-async-graphql-mongodb", "tide-async-graphql-mongodb"], " - Clean boilerplate for graphql services, with wasm/yew frontend."],
            li![link!["https://github.com/zzy/surfer", "surfer"], " - A blog built on yew + graphql, with ", link!["https://niqin.com", "live demo site"], ". Backend for graphql services, and frontend for web application."],
            li![link!["https://abhimanyu003.github.io/qubit", "qubit"], " - A handy calculator, based on Rust and WebAssembly, ", link!["https://abhimanyu003.github.io/qubit/", "Live Demo"], "."],
            li![link!["https://github.com/pmsanford/paudle", "Paudle"], " - A reimplementation of the excellent word game Wordle by Josh Wardle."],
            li![link!["https://github.com/Jondolf/rust-algorithms", "Rust algorithms"], " - A website with interactive implementations of various algorithms (only sorting algorithms for now)."],
            li![link!["https://gitlab.com/marcempunkt/maeurerdev", "Marc Portfolio"], " - A software developer portfolio, ", link!["https://maeurer.dev/", "Live Demo"], "."],
            li![link!["https://github.com/zzhack-stack/zzhack", "zzhack"], " - A personal blog, based on Rust & Yew, ", link!["https://www.zzhack.fun/technology", "Live Demo"], "."],
            li![link!["https://github.com/viz-rs/viz-rs.github.io", "viz.rs"], " - A website for viz web framework, ", link!["https://viz.rs/", "Live Demo"], "."],
            li![link!["https://github.com/lucasmerlin/hurlurl", "hurlurl"], " - A randomizing link shortener, ", link!["https://hurlurl.com/", "Live Demo"], "."],
            li![link!["https://github.com/tramlinehq/macige", "Macige"], " - CI workflow generator for mobile app development, ", link!["https://macige.tramline.app", "Live Demo"], "."],
            li![link!["https://github.com/eliaperantoni/spaceman", "Spaceman"], " - A cross-platform and graphical client for the gRPC communication protocol."],
        ],
        h2!["Templates"],
        ul![
            li![link!["https://github.com/jetli/create-yew-app", "Create Yew App"], " - Set up a modern Yew web app by running one command, ", code("npx create-yew-app my-app"), "."],
            li![link!["https://github.com/yewstack/yew-wasm-pack-template", "yew-wasm-pack-template"], " - A template for starting a Yew project to be used with wasm-pack."],
            li![link!["https://github.com/yewstack/yew-wasm-pack-minimal", "yew-wasm-pack-minimal"], " - A minimal template for starting a Yew project using wasm-bindgen and wasm-pack."],
            li![link!["https://github.com/spielrs/yew-parcel-template", "yew-parcel-template"], " - Awesome Yew with Yew-Router and Parcel application."],
        ],
        h2!["Crates"],
        h3!["Component Libraries"],
        ul![
            li![link!["https://github.com/dungeonfog/yew-mdc", "yew-mdc"], " - Material Design Components for the Yew framework."],
            li![link!["https://github.com/AlephAlpha/muicss-yew", "muicss-yew"], " - MUI-CSS Components for Yew framework."],
            li![link!["https://github.com/kellpossible/yew-bulma", "yew-bulma"], " - A Rust library providing components based on the bulma css library for projects using Yew."],
            li![link!["https://github.com/hamza1311/material-yew", "material-yew"], " - Yew wrapper for Material Web Components."],
            li![link!["https://github.com/cecton/yewprint", "Yewprint"], " - Port of blueprintjs.com to Yew."],
            li![link!["https://github.com/thedodd/ybc", "ybc"], " - A Yew component library based on the Bulma CSS framework."],
            li![link!["https://github.com/ctron/patternfly-yew", "patternfly-yew"], " - Patternfly components for Yew."],
            li![link!["https://github.com/pedrodesu/yew-feather", "yew-feather"], " - Feather Icons components for Yew."],
            li![link!["https://github.com/matiu2/tailwind-yew-builder", "tailwind-yew-builder"], " - Builds Tailwind CSS for Yew using docker-compose. Also supports Trunk."],
            li![link!["https://github.com/angular-rust/yew-components", "yew-components"], " - Material Design Components for the Yew framework."],
            li![link!["https://github.com/titanclass/yew-chart", "yew-chart"], " - A Yew-based charting library that provides SVG based components for rendering charts."],
        ],
        h3!["Components"],
        ul![
            li![link!["https://github.com/jfbilodeau/yew_form", "Yew Form"], " - Components to simplify handling forms with Yew."],
            li![link!["https://github.com/AircastDev/yew-component-size", "yew-component-size"], " - A Yew component that emits events when the parent component changes width/height."],
            li![link!["https://github.com/AircastDev/yew-virtual-scroller", "yew-virtual-scroller"], " - A Yew component for virtual scrolling / scroll windowing."],
            li![link!["https://crates.io/crates/yew-autoprops", "yew-autoprops"], " - proc-macro to automatically derive Properties structs from args for Yew components."],
        ],
        h3!["Hooks"],
        ul![
            li![link!["https://github.com/jetli/yew-hooks", "yew-hooks"], " - Custom Hooks library for Yew, inspired by ", link!["https://github.com/streamich/react-use", "streamich/react-use"], " and ", link!["https://github.com/alibaba/hooks", "alibaba/hooks"], "."],
            li![link!["https://github.com/futursolo/yew-side-effect", "yew-side-effect"], " - Reconcile Side Effects in Yew Applications, inspired by ", link!["https://github.com/gaearon/react-side-effect", "react-side-effect"], " and ", link!["https://github.com/nfl/react-helmet", "react-helmet"], "."],
            li![link!["https://github.com/futursolo/bounce", "Bounce"], " - The uncomplicated state management library for Yew, inspired by ", link!["https://github.com/reduxjs/redux", "Redux"], " and ", link!["https://github.com/facebookexperimental/Recoil", "Recoil"], "."],
        ],
        h3!["Utils"],
        ul![
            li![link!["https://github.com/intendednull/yewdux", "Yewdux"], " - Redux-like state containers for Yew apps."],
            li![link!["https://github.com/hobofan/reacty_yew", "reacty_yew"], " - Generate Yew components from React components via Typescript type definitions."],
            li![link!["https://github.com/IcyDefiance/styled-yew", "styled-yew"], " - CSS in Rust, similar to styled-components, but for Yew."],
            li![link!["https://github.com/futursolo/stylist-rs", "stylist-rs"], " - A CSS-in-Rust styling solution for WebAssembly Applications."],
            li![link!["https://github.com/Madoshakalaka/yew-interop", "Yew Interop"], " - Load JavaScript and CSS asynchronously in Yew."],
            li![link!["https://github.com/oovm/tailwind-rs", "Tailwind RS"], " - Tailwind style tracer in rust, JIT + AOT interpreter."],
        ],
        h3!["Wasm"],
        ul![
            li![link!["https://github.com/rustwasm/wasm-bindgen", "wasm-bindgen"], " - Facilitating high-level interactions between WebAssembly modules and JavaScript."],
            li![link!["https://github.com/koute/stdweb", "stdweb"], " - Provides Rust bindings to the Web APIs and to allow a high degree of interoperability between Rust and JavaScript."],
        ],
        h2!["Tooling"],
        ul![
            li![link!["https://github.com/rustwasm/wasm-pack", "wasm-pack"], " - Your favorite Rust -> WebAssembly workflow tool."],
            li![link!["https://github.com/jetli/wasm-pack-action", "wasm-pack-action"], " - Github action to install ", code("wasm-pack"), " by downloading the executable to speed up CI/CD."],
            li![link!["https://github.com/jetli/wasm-bindgen-action", "wasm-bindgen-action"], " - Github action to install ", code("wasm-bindgen"), " by downloading the executable to speed up CI/CD."],
            li![link!["https://github.com/koute/cargo-web", "cargo-web"], " - A Cargo subcommand for the client-side Web."],
            li![link!["https://github.com/thedodd/trunk", "Trunk"], " - Build, bundle & ship your Rust Wasm application to the web."],
            li![link!["https://github.com/jetli/trunk-action", "trunk-action"], " - Github action to install ", code("Trunk"), " by downloading the executable to speed up CI/CD."],
            li![link!["https://github.com/WebAssembly/wabt", "wabt"], " - The WebAssembly Binary Toolkit, for the ", code("wasm-strip"), " and ", code("wasm-objdump"), " tools to reduce .wasm file size."],
            li![link!["https://github.com/WebAssembly/binaryen", "binaryen"], " - Compiler infrastructure and toolchain library for WebAssembly, for the ", code("wasm-opt"), " tool to reduce .wasm file size."],
        ],
        h2!["Articles"],
        ul![
            li![link!["https://dev.to/deciduously/lets-build-a-rust-frontend-with-yew---part-1-3k2o", "Let's Build a Rust Frontend with Yew"]],
            li![link!["https://medium.com/@saschagrunert/a-web-application-completely-in-rust-6f6bdb6c4471", "A Web Application completely in Rust"]],
            li![link!["https://sudonull.com/post/11627-Yew-Rust-WebAsse-frontend-framework", "Yew - Rust & WebAsse-frontend framework"]],
            li![link!["https://dev.to/stevepryde/create-a-desktop-app-in-rust-using-tauri-and-yew-2bhe", "Create a desktop app in Rust using Tauri and Yew"]],
            li![link!["https://www.youtube.com/watch?v=ilrGIJGdqRo", "A code walkthrough video of Yew with a real-world app with Christopher Hunt and Kiki Carter"]],
        ],
        h2!["Books"],
        ul![
            li![link!["https://rustwasm.github.io/docs/book/", "The WebAssembly Book"], " - Working with the web and producing .wasm files."],
            li![link!["https://wasm-bindgen.github.io/wasm-bindgen/", "The wasm-bindgen Guide"], " - How to bind Rust and JavaScript APIs."],
            li![link!["https://drager.github.io/wasm-pack/book/", "The wasm-pack Guide"], " - How to build and work with rust-generated WebAssembly."],
            li![link!["https://pragprog.com/book/khrust/programming-webassembly-with-rust", "Programming WebAssembly with Rust"], " - Includes a chapter ", code("Advanced JavaScript Integration with Yew"), " on creating an app with Yew."],
            li![link!["https://www.oreilly.com/library/view/creative-projects-for/9781789346220/", "Creative Projects for Rust Programmers"], " - Chapter 5, ", code("Creating a Client-Side WebAssembly App Using Yew"), "."],
        ],
        h2!["Alternatives"],
        p!["Yew team love to share ideas with other projects and believe we can all help each other reach the full potential of this exciting new technology."],
        ul![
            li![link!["https://github.com/utkarshkukreti/draco", "Draco"], " - A Rust library for building client side web applications with WebAssembly."],
            li![link!["https://github.com/chinedufn/percy", "Percy"], " - A modular toolkit for building isomorphic web apps with Rust + WebAssembly."],
            li![link!["https://github.com/ivanceras/sauron", "Sauron"], " - Sauron is an HTML web framework for building web-apps."],
            li![link!["https://github.com/seed-rs/seed", "Seed"], " - A Rust framework for creating web apps."],
            li![link!["https://github.com/rbalicki2/smithy", "Smithy"], " - A framework for building WebAssembly apps in Rust."],
            li![link!["https://github.com/DioxusLabs/dioxus", "Dioxus"], " - Elegant React-like library for building user interfaces for desktop, web, mobile, SSR, liveview, and more."],
            li![link!["https://github.com/sycamore-rs/sycamore", "Sycamore"], " - A reactive library for creating web apps in Rust and WebAssembly."],
        ],
        h2!["Related lists"],
        ul![
            li![link!["https://github.com/rustwasm/awesome-rust-and-webassembly", "Awesome Rust and WebAssembly"], " - A list of awesome Rust and WebAssembly projects, libraries, tools, and resources."],
            li![link!["https://github.com/mbasso/awesome-wasm", "Awesome WebAssembly"], " - Collection of awesome things regarding WebAssembly ecosystem."],
            li![link!["https://github.com/rust-unofficial/awesome-rust", "Awesome Rust"], " - A curated list of Rust code and resources."],
        ],
    ])
);
