crate::community_page!("Awesome Yew",
    Content::new(vec![
        h2(vec![text("Projects")]),
        ul(vec![
            li(vec![link("https://github.com/alelavelli/rust-fullstack-web-application", vec![text("Fullstack application with infrastructure")]), text(" - Complete production-ready application with "), code("yew"), text(" as frontend, "), code("axum"), text(" as backend, "), code("docker compose"), text(" as infrastructure, "), code("mongodb"), text(" as database.")]),
            li(vec![link("https://github.com/jetli/rust-yew-realworld-example-app", vec![text("Realworld example")]), text(" - Exemplary real world app built with Rust + Yew + WebAssembly. It utilizes Yew's latest "), code("function components"), text(" and "), code("hooks"), text(". It also supports desktop application powered by "), link("https://github.com/tauri-apps/tauri", vec![text("Tauri")]), text(".")]),
            li(vec![link("https://github.com/saschagrunert/webapp.rs", vec![text("webapp.rs")]), text(" - A web application completely written in Rust, frontend is built with Yew.")]),
            li(vec![link("https://github.com/steadylearner/Rust-Full-Stack", vec![text("Rust-Full-Stack")]), text(" - Easily testable and working Rust codes with blog posts to explain them.")]),
            li(vec![link("https://github.com/hgzimmerman/BucketQuestions", vec![text("Bucket Questions")]), text(" - A webapp written entirely in Rust for a dumb party game.")]),
            li(vec![link("https://github.com/Extrawurst/rust-webview-todomvc-yew", vec![text("web-view todomvc desktop app")]), text(" - Demo how to use yew for a todomvc that compiles to WebAssembly and is bundled as a lightweight(~2mb) desktop app by "), link("https://github.com/Boscop/web-view", vec![text("web-view")]), text(", as an alternative to Electron, "), link("https://github.com/Boscop/web-view", vec![text("web-view")]), text(" also has a "), link("https://github.com/Boscop/web-view/tree/master/webview-examples/examples#todo-yew", vec![text("demo")]), text(".")]),
            li(vec![link("https://github.com/hobofan/yew-react-example", vec![text("yew-react-example")]), text(" - This project shows how to create a web app using a React component inside a Yew component.")]),
            li(vec![link("https://github.com/stkevintan/Kirk", vec![text("Kirk")]), text(" - Just A Rust WebAssembly Blog.")]),
            li(vec![link("https://github.com/extraymond/rust-async-wasm-demo", vec![text("rust-async-wasm-demo")]), text(" - Toy project to learn Rust and async that can be deployed to the web.")]),
            li(vec![link("https://github.com/tarkah/karaoke-rs", vec![text("karaoke-rs")]), text(" - A simple, network enabled karaoke player in Rust.")]),
            li(vec![link("https://github.com/noc7c9/i-love-hue-rs", vec![text("I Love Hue! (rs)")]), text(" - A clone of the mobile game I Love Hue in Yew (Rust).")]),
            li(vec![link("https://github.com/spielrs/yew-styles-page", vec![text("yew-styles-page")]), text(" - This is an initial project of a framework style for yew.")]),
            li(vec![link("https://github.com/jplatte/caniuse.rs", vec![text("caniuse.rs")]), text(" - Rust feature search.")]),
            li(vec![link("https://github.com/Extrawurst/rust-electron-demo", vec![text("Rust electron yew demo")]), text(" - An example of building a Rust based web app (Yew) into a native app using electron.")]),
            li(vec![link("https://github.com/jbowens/covplot", vec![text("covplot")]), text(" - Live graphs of worldwide CoVID-19 data.")]),
            li(vec![link("https://github.com/fadhlika/tanoshi-web", vec![text("Tanoshi")]), text(" - Tachiyomi-like web manga reader. Front-end for tanoshi.")]),
            li(vec![link("https://github.com/jgpaiva/minesweeper", vec![text("Minesweeper")]), text(" - Minesweeper built with Rust, Yew and WebAssembly.")]),
            li(vec![link("https://github.com/Stigjb/freecell", vec![text("Freecell")]), text(" - A patience game written in Rust and Yew.")]),
            li(vec![link("https://github.com/MTRNord/Daydream", vec![text("Daydream")]), text(" - A small Matrix web client written in Rust.")]),
            li(vec![link("https://github.com/codec-abc/Yew-WebRTC-Chat", vec![text("Yew-WebRTC-Chat")]), text(" - A simple WebRTC chat made with Yew.")]),
            li(vec![link("https://github.com/lukidoescode/yew-fullstack-boilerplate", vec![text("Yew Fullstack Boilerplate")]), text(" - Highly opinionated boilerplate for creating full stack applications with Rust.")]),
            li(vec![link("https://github.com/Stigjb/chord-quiz", vec![text("Chord Quiz")]), text(" - Practice recognizing chords in this Rust/Yew/WebAssembly app.")]),
            li(vec![link("https://github.com/sheshbabu/rustmart-yew-example", vec![text("RustMart")]), text(" - Single Page Application (SPA) written using Rust, Wasm and Yew.")]),
            li(vec![link("https://github.com/alepez/devand", vec![text("DevAndDev")]), text(" - A website where developers can find pair-programming partners. Written in Rust, Yew frontend.")]),
            li(vec![link("https://github.com/io12/yew-octicons", vec![text("yew-octicons")]), text(" - An easy interface for using Octicons in Yew projects.")]),
            li(vec![link("https://github.com/pipe-fun/pipe", vec![text("Pipe")]), text(" - This is a Rust / Wasm client web app which is a task control center.")]),
            li(vec![link("https://github.com/oovm/note-to-yew", vec![text("note-to-yew")]), text(" - Convert your markups into Yew macro online, which is also made by Yew.")]),
            li(vec![link("https://github.com/getreu/ascii-hangman", vec![text("ASCII-Hangman")]), text(" - Configurable Hangman game for children with ASCII-art rewarding.")]),
            li(vec![link("https://github.com/shaunbennett/dotdotyew", vec![text("dotdotyew")]), text(" - "), link("https://en.wikipedia.org/wiki/Dot-voting", vec![text("Dot-voting")]), text(" using Yew, with Rust powering the backend API.")]),
            li(vec![link("https://github.com/dev-family/wasm-2048", vec![text("wasm-2048")]), text(" - 2048 game implemented with Rust and Yew and compiled to Wasm.")]),
            li(vec![link("https://github.com/kamiyaa/website-wasm", vec![text("website-wasm")]), text(" - My personal website written in Rust via Yew/Wasm.")]),
            li(vec![link("https://github.com/rayylee/keypress", vec![text("KeyPress")]), text(" - A Rust WebAssembly Website example for practising english for chinese.")]),
            li(vec![link("https://github.com/anthhub/yew-train-ticket", vec![text("yew-train-ticket")]), text(" - A Rust WebAssembly Webapp example basing Yew newest hooks and functional API, the code style is extremely like React Function Component.")]),
            li(vec![link("https://github.com/ivanschuetz/yew-d3-example", vec![text("yew-d3-example")]), text(" - Showing a d3 chart with Yew.")]),
            li(vec![link("https://github.com/sanpii/oxfeed", vec![text("Oxfeed")]), text(" - A feed reader written in Rust with a Yew frontend.")]),
            li(vec![link("https://github.com/LighghtEeloo/flow.er", vec![text("Flow.er")]), text(" - A notebook app integrated with todo lists utility. Developed with Rust, WebAssembly, Yew and Trunk.")]),
            li(vec![link("https://github.com/vascokk/fullstack-rust", vec![text("Fullstack-Rust")]), text(" - A Full Stack Rust application (Connect5 game) with Actix-web, Yew, Bulma CSS and Diesel.")]),
            li(vec![link("https://github.com/MAE664128/sea_battle", vec![text("Sea_battle")]), text(" - A simple example of a sea battle game. Rust + Yew.")]),
            li(vec![link("https://github.com/zzy/tide-async-graphql-mongodb", vec![text("tide-async-graphql-mongodb")]), text(" - Clean boilerplate for graphql services, with wasm/yew frontend.")]),
            li(vec![link("https://github.com/zzy/surfer", vec![text("surfer")]), text(" - A blog built on yew + graphql, with "), link("https://niqin.com", vec![text("live demo site")]), text(". Backend for graphql services, and frontend for web application.")]),
            li(vec![link("https://abhimanyu003.github.io/qubit", vec![text("qubit")]), text(" - A handy calculator, based on Rust and WebAssembly, "), link("https://abhimanyu003.github.io/qubit/", vec![text("Live Demo")]), text(".")]),
            li(vec![link("https://github.com/pmsanford/paudle", vec![text("Paudle")]), text(" - A reimplementation of the excellent word game Wordle by Josh Wardle.")]),
            li(vec![link("https://github.com/Jondolf/rust-algorithms", vec![text("Rust algorithms")]), text(" - A website with interactive implementations of various algorithms (only sorting algorithms for now).")]),
            li(vec![link("https://gitlab.com/marcempunkt/maeurerdev", vec![text("Marc Portfolio")]), text(" - A software developer portfolio, "), link("https://maeurer.dev/", vec![text("Live Demo")]), text(".")]),
            li(vec![link("https://github.com/zzhack-stack/zzhack", vec![text("zzhack")]), text(" - A personal blog, based on Rust & Yew, "), link("https://www.zzhack.fun/technology", vec![text("Live Demo")]), text(".")]),
            li(vec![link("https://github.com/viz-rs/viz-rs.github.io", vec![text("viz.rs")]), text(" - A website for viz web framework, "), link("https://viz.rs/", vec![text("Live Demo")]), text(".")]),
            li(vec![link("https://github.com/lucasmerlin/hurlurl", vec![text("hurlurl")]), text(" - A randomizing link shortener, "), link("https://hurlurl.com/", vec![text("Live Demo")]), text(".")]),
            li(vec![link("https://github.com/tramlinehq/macige", vec![text("Macige")]), text(" - CI workflow generator for mobile app development, "), link("https://macige.tramline.app", vec![text("Live Demo")]), text(".")]),
            li(vec![link("https://github.com/eliaperantoni/spaceman", vec![text("Spaceman")]), text(" - A cross-platform and graphical client for the gRPC communication protocol.")]),
        ]),
        h2(vec![text("Templates")]),
        ul(vec![
            li(vec![link("https://github.com/jetli/create-yew-app", vec![text("Create Yew App")]), text(" - Set up a modern Yew web app by running one command, "), code("npx create-yew-app my-app"), text(".")]),
            li(vec![link("https://github.com/yewstack/yew-wasm-pack-template", vec![text("yew-wasm-pack-template")]), text(" - A template for starting a Yew project to be used with wasm-pack.")]),
            li(vec![link("https://github.com/yewstack/yew-wasm-pack-minimal", vec![text("yew-wasm-pack-minimal")]), text(" - A minimal template for starting a Yew project using wasm-bindgen and wasm-pack.")]),
            li(vec![link("https://github.com/spielrs/yew-parcel-template", vec![text("yew-parcel-template")]), text(" - Awesome Yew with Yew-Router and Parcel application.")]),
        ]),
        h2(vec![text("Crates")]),
        h3(vec![text("Component Libraries")]),
        ul(vec![
            li(vec![link("https://github.com/dungeonfog/yew-mdc", vec![text("yew-mdc")]), text(" - Material Design Components for the Yew framework.")]),
            li(vec![link("https://github.com/AlephAlpha/muicss-yew", vec![text("muicss-yew")]), text(" - MUI-CSS Components for Yew framework.")]),
            li(vec![link("https://github.com/kellpossible/yew-bulma", vec![text("yew-bulma")]), text(" - A Rust library providing components based on the bulma css library for projects using Yew.")]),
            li(vec![link("https://github.com/hamza1311/material-yew", vec![text("material-yew")]), text(" - Yew wrapper for Material Web Components.")]),
            li(vec![link("https://github.com/cecton/yewprint", vec![text("Yewprint")]), text(" - Port of blueprintjs.com to Yew.")]),
            li(vec![link("https://github.com/thedodd/ybc", vec![text("ybc")]), text(" - A Yew component library based on the Bulma CSS framework.")]),
            li(vec![link("https://github.com/ctron/patternfly-yew", vec![text("patternfly-yew")]), text(" - Patternfly components for Yew.")]),
            li(vec![link("https://github.com/pedrodesu/yew-feather", vec![text("yew-feather")]), text(" - Feather Icons components for Yew.")]),
            li(vec![link("https://github.com/matiu2/tailwind-yew-builder", vec![text("tailwind-yew-builder")]), text(" - Builds Tailwind CSS for Yew using docker-compose. Also supports Trunk.")]),
            li(vec![link("https://github.com/angular-rust/yew-components", vec![text("yew-components")]), text(" - Material Design Components for the Yew framework.")]),
            li(vec![link("https://github.com/titanclass/yew-chart", vec![text("yew-chart")]), text(" - A Yew-based charting library that provides SVG based components for rendering charts.")]),
        ]),
        h3(vec![text("Components")]),
        ul(vec![
            li(vec![link("https://github.com/jfbilodeau/yew_form", vec![text("Yew Form")]), text(" - Components to simplify handling forms with Yew.")]),
            li(vec![link("https://github.com/AircastDev/yew-component-size", vec![text("yew-component-size")]), text(" - A Yew component that emits events when the parent component changes width/height.")]),
            li(vec![link("https://github.com/AircastDev/yew-virtual-scroller", vec![text("yew-virtual-scroller")]), text(" - A Yew component for virtual scrolling / scroll windowing.")]),
            li(vec![link("https://crates.io/crates/yew-autoprops", vec![text("yew-autoprops")]), text(" - proc-macro to automatically derive Properties structs from args for Yew components.")]),
        ]),
        h3(vec![text("Hooks")]),
        ul(vec![
            li(vec![link("https://github.com/jetli/yew-hooks", vec![text("yew-hooks")]), text(" - Custom Hooks library for Yew, inspired by "), link("https://github.com/streamich/react-use", vec![text("streamich/react-use")]), text(" and "), link("https://github.com/alibaba/hooks", vec![text("alibaba/hooks")]), text(".")]),
            li(vec![link("https://github.com/futursolo/yew-side-effect", vec![text("yew-side-effect")]), text(" - Reconcile Side Effects in Yew Applications, inspired by "), link("https://github.com/gaearon/react-side-effect", vec![text("react-side-effect")]), text(" and "), link("https://github.com/nfl/react-helmet", vec![text("react-helmet")]), text(".")]),
            li(vec![link("https://github.com/futursolo/bounce", vec![text("Bounce")]), text(" - The uncomplicated state management library for Yew, inspired by "), link("https://github.com/reduxjs/redux", vec![text("Redux")]), text(" and "), link("https://github.com/facebookexperimental/Recoil", vec![text("Recoil")]), text(".")]),
        ]),
        h3(vec![text("Utils")]),
        ul(vec![
            li(vec![link("https://github.com/intendednull/yewdux", vec![text("Yewdux")]), text(" - Redux-like state containers for Yew apps.")]),
            li(vec![link("https://github.com/hobofan/reacty_yew", vec![text("reacty_yew")]), text(" - Generate Yew components from React components via Typescript type definitions.")]),
            li(vec![link("https://github.com/IcyDefiance/styled-yew", vec![text("styled-yew")]), text(" - CSS in Rust, similar to styled-components, but for Yew.")]),
            li(vec![link("https://github.com/futursolo/stylist-rs", vec![text("stylist-rs")]), text(" - A CSS-in-Rust styling solution for WebAssembly Applications.")]),
            li(vec![link("https://github.com/Madoshakalaka/yew-interop", vec![text("Yew Interop")]), text(" - Load JavaScript and CSS asynchronously in Yew.")]),
            li(vec![link("https://github.com/oovm/tailwind-rs", vec![text("Tailwind RS")]), text(" - Tailwind style tracer in rust, JIT + AOT interpreter.")]),
        ]),
        h3(vec![text("Wasm")]),
        ul(vec![
            li(vec![link("https://github.com/rustwasm/wasm-bindgen", vec![text("wasm-bindgen")]), text(" - Facilitating high-level interactions between WebAssembly modules and JavaScript.")]),
            li(vec![link("https://github.com/koute/stdweb", vec![text("stdweb")]), text(" - Provides Rust bindings to the Web APIs and to allow a high degree of interoperability between Rust and JavaScript.")]),
        ]),
        h2(vec![text("Tooling")]),
        ul(vec![
            li(vec![link("https://github.com/rustwasm/wasm-pack", vec![text("wasm-pack")]), text(" - Your favorite Rust -> WebAssembly workflow tool.")]),
            li(vec![link("https://github.com/jetli/wasm-pack-action", vec![text("wasm-pack-action")]), text(" - Github action to install "), code("wasm-pack"), text(" by downloading the executable to speed up CI/CD.")]),
            li(vec![link("https://github.com/jetli/wasm-bindgen-action", vec![text("wasm-bindgen-action")]), text(" - Github action to install "), code("wasm-bindgen"), text(" by downloading the executable to speed up CI/CD.")]),
            li(vec![link("https://github.com/koute/cargo-web", vec![text("cargo-web")]), text(" - A Cargo subcommand for the client-side Web.")]),
            li(vec![link("https://github.com/thedodd/trunk", vec![text("Trunk")]), text(" - Build, bundle & ship your Rust Wasm application to the web.")]),
            li(vec![link("https://github.com/jetli/trunk-action", vec![text("trunk-action")]), text(" - Github action to install "), code("Trunk"), text(" by downloading the executable to speed up CI/CD.")]),
            li(vec![link("https://github.com/WebAssembly/wabt", vec![text("wabt")]), text(" - The WebAssembly Binary Toolkit, for the "), code("wasm-strip"), text(" and "), code("wasm-objdump"), text(" tools to reduce .wasm file size.")]),
            li(vec![link("https://github.com/WebAssembly/binaryen", vec![text("binaryen")]), text(" - Compiler infrastructure and toolchain library for WebAssembly, for the "), code("wasm-opt"), text(" tool to reduce .wasm file size.")]),
        ]),
        h2(vec![text("Articles")]),
        ul(vec![
            li(vec![link("https://dev.to/deciduously/lets-build-a-rust-frontend-with-yew---part-1-3k2o", vec![text("Let's Build a Rust Frontend with Yew")])]),
            li(vec![link("https://medium.com/@saschagrunert/a-web-application-completely-in-rust-6f6bdb6c4471", vec![text("A Web Application completely in Rust")])]),
            li(vec![link("https://sudonull.com/post/11627-Yew-Rust-WebAsse-frontend-framework", vec![text("Yew - Rust & WebAsse-frontend framework")])]),
            li(vec![link("https://dev.to/stevepryde/create-a-desktop-app-in-rust-using-tauri-and-yew-2bhe", vec![text("Create a desktop app in Rust using Tauri and Yew")])]),
            li(vec![link("https://www.youtube.com/watch?v=ilrGIJGdqRo", vec![text("A code walkthrough video of Yew with a real-world app with Christopher Hunt and Kiki Carter")])]),
        ]),
        h2(vec![text("Books")]),
        ul(vec![
            li(vec![link("https://rustwasm.github.io/docs/book/", vec![text("The WebAssembly Book")]), text(" - Working with the web and producing .wasm files.")]),
            li(vec![link("https://wasm-bindgen.github.io/wasm-bindgen/", vec![text("The wasm-bindgen Guide")]), text(" - How to bind Rust and JavaScript APIs.")]),
            li(vec![link("https://drager.github.io/wasm-pack/book/", vec![text("The wasm-pack Guide")]), text(" - How to build and work with rust-generated WebAssembly.")]),
            li(vec![link("https://pragprog.com/book/khrust/programming-webassembly-with-rust", vec![text("Programming WebAssembly with Rust")]), text(" - Includes a chapter "), code("Advanced JavaScript Integration with Yew"), text(" on creating an app with Yew.")]),
            li(vec![link("https://www.oreilly.com/library/view/creative-projects-for/9781789346220/", vec![text("Creative Projects for Rust Programmers")]), text(" - Chapter 5, "), code("Creating a Client-Side WebAssembly App Using Yew"), text(".")]),
        ]),
        h2(vec![text("Alternatives")]),
        p(vec![text("Yew team love to share ideas with other projects and believe we can all help each other reach the full potential of this exciting new technology.")]),
        ul(vec![
            li(vec![link("https://github.com/utkarshkukreti/draco", vec![text("Draco")]), text(" - A Rust library for building client side web applications with WebAssembly.")]),
            li(vec![link("https://github.com/chinedufn/percy", vec![text("Percy")]), text(" - A modular toolkit for building isomorphic web apps with Rust + WebAssembly.")]),
            li(vec![link("https://github.com/ivanceras/sauron", vec![text("Sauron")]), text(" - Sauron is an HTML web framework for building web-apps.")]),
            li(vec![link("https://github.com/seed-rs/seed", vec![text("Seed")]), text(" - A Rust framework for creating web apps.")]),
            li(vec![link("https://github.com/rbalicki2/smithy", vec![text("Smithy")]), text(" - A framework for building WebAssembly apps in Rust.")]),
            li(vec![link("https://github.com/DioxusLabs/dioxus", vec![text("Dioxus")]), text(" - Elegant React-like library for building user interfaces for desktop, web, mobile, SSR, liveview, and more.")]),
            li(vec![link("https://github.com/sycamore-rs/sycamore", vec![text("Sycamore")]), text(" - A reactive library for creating web apps in Rust and WebAssembly.")]),
        ]),
        h2(vec![text("Related lists")]),
        ul(vec![
            li(vec![link("https://github.com/rustwasm/awesome-rust-and-webassembly", vec![text("Awesome Rust and WebAssembly")]), text(" - A list of awesome Rust and WebAssembly projects, libraries, tools, and resources.")]),
            li(vec![link("https://github.com/mbasso/awesome-wasm", vec![text("Awesome WebAssembly")]), text(" - Collection of awesome things regarding WebAssembly ecosystem.")]),
            li(vec![link("https://github.com/rust-unofficial/awesome-rust", vec![text("Awesome Rust")]), text(" - A curated list of Rust code and resources.")]),
        ]),
    ])
);
