name: Clippy

on:
  pull_request:
    paths:
      - ".github/workflows/clippy.yml"
      - "tools/**/*"
      - "examples/**/*"
      - "packages/**/*"
      - "Cargo.toml"
      - "Cargo.lock"
  push:
    branches: [master]

jobs:
  feature-soundness:
    name: Feature Soundness
    runs-on: ubuntu-latest
    # if normal clippy doesn't succeed, do not try to lint feature soundness
    needs: clippy

    strategy:
      fail-fast: false
      matrix:
        profile:
          - dev
          - release
        target:
          - host
          - wasm32
    steps:
      - uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
          targets: ${{ case(matrix.target == 'wasm32', 'wasm32-unknown-unknown', null) }}

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - uses: taiki-e/install-action@cargo-hack

      - name: Lint feature soundness
        env:
          RELEASE_FLAG: ${{ case(matrix.profile == 'release', '--release', null) }}
          TARGET_FLAGS: ${{ case(matrix.target == 'wasm32', '--target wasm32-unknown-unknown', null) }}
        run: >-
          cargo hack clippy
          -p yew -p yew-agent -p yew-router -p yew-link
          --feature-powerset --no-dev-deps
          --keep-going
          $RELEASE_FLAG
          $TARGET_FLAGS
          -- -D warnings

  clippy:
    name: Clippy Workspace
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Run clippy
        run: |
          cargo clippy \
            --all-targets \
            --all-features \
            --workspace \
            -- -D warnings
